export const imagePath = {
  calendarIcon: require('../assets/calendarIcon.png'),
  displayIcon: require('../assets/displayIcon.png'),
  feedbackIcon: require('../assets/feedbackIcon.png'),
  profileIcon: require('../assets/profileIcon.png'),

  PhoneNoLogin: require('../assets/logos/LoginPhone.png'),
  FacebookLogin: require('../assets/logos/LoginFacebook.png'),
  GoogleLogin: require('../assets/logos/LoginGoogle.png'),
  AppleLogin: require('../assets/logos/LoginApple.png'),
  facebookIcon: require('../assets/logos/facebookIcon.png'),
  GoogleIcon: require('../assets/logos/GoogleIcon.png'),
  arrow: require('../assets/logos/arrow.png'),
  GoogleIcon: require('../assets/logos/GoogleIcon.png'),
  SignInBtn: require('../assets/logos/SignInBtn.png'),
  DSignINBtn: require('../assets/logos/DSignINBtn.png'),
  DSignUp: require('../assets/logos/DSignUp.png'),
  DFacebookBtn: require('../assets/logos/DFacebookBtn.png'),
  DPhoneNo: require('../assets/logos/DPhoneNo.png'),
  DGoogle: require('../assets/logos/DGoogle.png'),
  Dapple: require('../assets/logos/Dapple.png'),
  DApplecenter: require('../assets/logos/DApplecenter.png'),
  AppleCenter: require('../assets/logos/AppleCenter.png'),
};
